name: Replace HYPHEN to NON-BREAKING HYPHEN
on: [push, pull_request]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: List all files
      #   run: find . -type f -name "*.md"
      # - name: Display contents before replacement
      #   run: find . -type f -name "*.md" -exec cat {} +
      - name: Replace string in file
        run: |
          find . -type f -name "*.md" -exec sed -i 's/e/./g' {} +
      # - name: Display contents after replacement
      #   run: find . -type f -name "*.md" -exec cat {} +
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Replace hyphen with non-breaking hyphen"
          file_pattern: "*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # uses: MathieuSoysal/replace-string-in-file@v1.1.0
        # with:
        #   file: "**/*"
        #   old-string: "space"
        #   new-string: "espacio"

# name: Replace HYPHEN to NON-BREAKING HYPHEN
# on: [push, pull_request]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
#       - name: Find and Replace
#         uses: jacobtomlinson/gha-find-replace@v3
#         with:
#           find: "—"
#           replace: "."
#           regex: false
#           exclude: . # Do not modify this file
#       - name: Push changes
#         uses: stefanzweifel/git-auto-commit-action@v4
